require:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.5
  SuggestExtensions: false
  NewCops: enable
  Exclude:
    - 'vendor/**/*'

Style:
  Enabled: false

Metrics/AbcSize:
  Max: 25

RSpec/SubjectStub:
  Exclude:
    - 'spec/snov/get_emails_from_name_spec.rb'